# Generated by Django 3.0 on 2021-04-14 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210414_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_nurse',
        ),
    ]
