# Generated by Django 3.0 on 2021-04-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_is_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_nurse',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
