# Generated by Django 3.0 on 2021-09-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210930_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ManyToManyField(blank=True, null=True, to='api.Doctor'),
        ),
    ]
