# Generated by Django 3.0 on 2021-05-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210507_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='zip_code',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
