# Generated by Django 3.0 on 2021-05-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_patient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
    ]
