# Generated by Django 3.0 on 2021-05-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210512_1521'),
        ('api', '0015_auto_20210512_1506'),
    ]

    operations = [
    ]
