# Generated by Django 3.0 on 2021-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20210512_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('check_in', 'check_in'), ('check_out', 'check_out')], default='inactive', max_length=10),
        ),
    ]
